Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"  # Specify the base box
  config.vm.synced_folder "./shared", "/home/vagrant/shared_guest"
  config.vm.network "private_network", ip: "192.168.56.10"  # Network settings
  config.vm.provider "virtualbox" do |vb|
    vb.name = "Vagrant_VM2"
    vb.memory = "4096"  # Set RAM
    vb.cpus = 4  # Set CPU
  end
  config.vm.provision "shell", path: "setup.sh"
end
