apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: falco
  namespace: kube-system
  labels:
    app: falco
spec:
  selector:
    matchLabels:
      app: falco
  template:
    metadata:
      labels:
        app: falco
    spec:
      serviceAccountName: falco
      hostPID: true
      tolerations:
        - operator: "Exists"
      containers:
        - name: falco
          image: falcosecurity/falco:latest
          securityContext:
            privileged: true
          resources:
            limits:
              memory: "256Mi"
              cpu: "100m"
            requests:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts:
            - name: docker
              mountPath: /host/var/run/docker.sock
            - name: proc
              mountPath: /host/proc
            - name: boot
              mountPath: /host/boot
            - name: libmodules
              mountPath: /host/lib/modules
            - name: usr
              mountPath: /host/usr
      volumes:
        - name: docker
          hostPath:
            path: /var/run/docker.sock
        - name: proc
          hostPath:
            path: /proc
        - name: boot
          hostPath:
            path: /boot
        - name: libmodules
          hostPath:
            path: /lib/modules
        - name: usr
          hostPath:
            path: /usr
