Vagrant.configure("2") do |config|
  (1..3).each do |i| 
    node_name = "node#{i}"
    vm_name = "VM_#{i}"  

    config.vm.define node_name do |node|
      node.vm.box = "bento/ubuntu-24.04"
      node.vm.synced_folder "./shared", "/home/vagrant/shared_guest"
      node.vm.network "public_network", type: "dhcp", bridge: "en0: Wi-Fi"
      
      node.vm.provider "virtualbox" do |vb|
        vb.name = vm_name  
        vb.memory = "2048"
        vb.cpus = 2  
      end
    end
  end
end
