Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"  # Specify the base box
  config.vm.synced_folder "./shared", "/home/vagrant/shared_guest"
  config.vm.network "public_network", ip: "192.168.56.11", bridge: "en0: Wi-Fi"  # Network settings
  config.vm.provider "virtualbox" do |vb|
    vb.name = "Vagrant_VM3"
    vb.memory = "4096"  # Set RAM
    vb.cpus = 4  # Set CPU
  end
end
