Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"  # Specify the base box
  config.vm.synced_folder "./shared", "/home/vagrant/shared_guest"
  config.vm.network "public_network", type: "dhcp"  # Network settings
  config.vm.provider "virtualbox" do |vb|
    vb.name = "Vagrant_VM1"
    vb.memory = "4096"  # Set RAM
    vb.cpus = 4  # Set CPU
  end
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update -y
    sudo apt-get install -y apache2
  SHELL
end
